/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan_hibernate_qlsv;

import DAO.DKMHDAO;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entities.*;
import DAO.*;
import javassist.bytecode.stackmap.BasicBlock;
/**
 *
 * @author Admin
 */
public class DangKyWindow extends javax.swing.JPanel {

    /**
     * Creates new form DangKyWindow
     */
    String lineAll;
    String lopHoc="";
    String maMH="";
    DKMHDAO dKMHDAO=new DKMHDAO();
    SinhVienDAO svDAO=new SinhVienDAO();
    public DangKyWindow() throws IOException {
        initComponents();
       load();
       
    }
    public  void load(){
        loadData();
        loadCbLop();
       
    }
    public void loadCbLop()
    {
        cbLop.removeAllItems();
        List<String> lsCB=dKMHDAO.layMaLop();
        for(String s : lsCB){
            cbLop.addItem(s);
        }
        
    }
    private void loadData()
    {
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("STT");
        dtm.addColumn("Ma Lop");
        dtm.addColumn("Ma Mon");
        dtm.addColumn("MaSV");
        dtm.addColumn("Ho Ten");
        dtm.addColumn("Gioi Tinh");
        dtm.addColumn("CMND");  
         for(entities.Dkmh dkmh : this.dKMHDAO.load_danhSach())
        {
            dtm.addRow(new Object[]{dkmh.getStt(),dkmh.getId().getMaLop(),dkmh.getId().getMaMon(),dkmh.getId().getMaSv(),
            dkmh.getHoTen(),dkmh.getGioiTinh(),dkmh.getCmnd()             });
            
        }
        this.tbMonHoc.setModel(dtm);
        this.tbMonHoc.repaint();
        this.tbMonHoc.revalidate();
    }
    public  void loadCbMonHoc(String maLop){
        cbDSMH.removeAllItems();
        List<String> lsCB=dKMHDAO.layTenMonHoc(maLop);
        for(int i=0;i<lsCB.size();i++){
            cbDSMH.addItem(lsCB.get(i));
        }
    }
    private void loadDataTimKiem(String maLOp, String tenMonHoc)
    {
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("STT");
        dtm.addColumn("Ma Lop");
        dtm.addColumn("Ma Mon");
        dtm.addColumn("MaSV");
        dtm.addColumn("Ho Ten");
        dtm.addColumn("Gioi Tinh");
        dtm.addColumn("CMND");  
         for(entities.Dkmh dkmh : this.dKMHDAO.layThongTinDangKy(maLOp, tenMonHoc))
        {
            dtm.addRow(new Object[]{dkmh.getStt(),dkmh.getId().getMaLop(),dkmh.getId().getMaMon(),dkmh.getId().getMaSv(),
            dkmh.getHoTen(),dkmh.getGioiTinh(),dkmh.getCmnd()             });
            
        }
        this.tbMonHoc.setModel(dtm);
        this.tbMonHoc.repaint();
        this.tbMonHoc.revalidate();
    }  
     public void docFile(String p) throws FileNotFoundException, IOException{
        DefaultTableModel dtm=new DefaultTableModel();      
        
        File fileDir = new File(p);
			
		BufferedReader br = new BufferedReader(
		   new InputStreamReader(
                      new FileInputStream(fileDir), "UTF8"));
        String [] NameSV;
        String []dataSV;
        String line = br.readLine();
        NameSV=line.split(",");
        for(int i=0;i<NameSV.length;i++){
            dtm.addColumn(String.valueOf(NameSV[i]));
        }         
        line = br.readLine();
          while(line != null){
              dataSV=line.split(",");
               dtm.addRow(new Object[]{dataSV[0],dataSV[1],dataSV[2],dataSV[3],dataSV[4]});
              line =br.readLine();
          }
        br.close();
        //fr.close();
         this.tbMonHoc.setModel(dtm);
        this.tbMonHoc.repaint();
        this.tbMonHoc.revalidate();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        lbThongBao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnThemSV = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbLop = new javax.swing.JComboBox();
        cbDSMH = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMonHoc = new javax.swing.JTable();
        btnHuyMH = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setLayout(null);

        lbThongBao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbThongBao.setText("Quản Lý Đăng Ký Môn Học");
        add(lbThongBao);
        lbThongBao.setBounds(250, 10, 550, 22);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel4.setText("MSSV");

        jLabel5.setText("Họ tên");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        jLabel6.setText("Giới Tính");

        buttonGroup1.add(rdNam);
        rdNam.setText("Nam");
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNu);
        rdNu.setText("Nư");

        jLabel7.setText("CMND");

        btnThemSV.setText("Thêm");
        btnThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSVActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Lơp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtMaLop))
                            .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(rdNam)
                        .addGap(31, 31, 31)
                        .addComponent(rdNu))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(jLabel4)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdNam)
                    .addComponent(rdNu)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        add(jPanel1);
        jPanel1.setBounds(10, 60, 310, 420);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Lớp");

        jLabel3.setText("Môn Học");

        cbLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLopItemStateChanged(evt);
            }
        });

        cbDSMH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDSMHItemStateChanged(evt);
            }
        });

        tbMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbMonHoc);

        btnHuyMH.setBackground(new java.awt.Color(255, 102, 102));
        btnHuyMH.setText("Huỷ Môn");
        btnHuyMH.setToolTipText("Chọn Vào Dòng Sinh Viên  Cần Huỷ Môn Học . ");
        btnHuyMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57)
                        .addComponent(cbDSMH, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnHuyMH, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDSMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHuyMH)
                .addContainerGap())
        );

        add(jPanel2);
        jPanel2.setBounds(340, 80, 640, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNamActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void cbLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLopItemStateChanged
        if(cbLop.getSelectedItem()!=null){
            String maLop = cbLop.getSelectedItem().toString();
           // JOptionPane.showMessageDialog(cbLop,"kq="+maLop);
            loadCbMonHoc(maLop);
        }
    }//GEN-LAST:event_cbLopItemStateChanged

    private void cbDSMHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDSMHItemStateChanged

    }//GEN-LAST:event_cbDSMHItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String maLop=cbLop.getSelectedItem().toString();
        String maMonHoc=cbDSMH.getSelectedItem().toString();
        loadDataTimKiem(maLop,maMonHoc);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String  mssv=txtMSSV.getText();  
        try{
            Sinhvien sv=svDAO.load(mssv);
            txtCMND.setText(String.valueOf(sv.getCmnd()));
            txtHoTen.setText(sv.getHoTen());
            txtMaLop.setText(sv.getMaLop());
            if(sv.getGioiTinh().equals("Nam")){
                rdNam.setSelected(true);
            }else{
                rdNu.setSelected(true);
              
            }
        } catch(Exception e){
                    JOptionPane.showMessageDialog(cbLop,"Sv khong ton tai");
         }
        
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuyMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyMHActionPerformed
       try{
            String msMOn = this.tbMonHoc.getValueAt(this.tbMonHoc.getSelectedRow(),2).toString();   
            String msLop = this.tbMonHoc.getValueAt(this.tbMonHoc.getSelectedRow(),1).toString();   
            String msSV = this.tbMonHoc.getValueAt(this.tbMonHoc.getSelectedRow(),3).toString();  
            DkmhId dkmhId=new DkmhId(msLop, msMOn, msSV);

            Dkmh dkmh=dKMHDAO.load(dkmhId);       
            dKMHDAO.delete(dkmh);
            JOptionPane.showMessageDialog(cbLop,"Huy Mon Thanh Cong");
       }catch(Exception e){
           JOptionPane.showMessageDialog(cbLop,"Chon Dong Sinh Vien Can Huy Mon");
       }
       
    }//GEN-LAST:event_btnHuyMHActionPerformed
    public  boolean kiemTra(){
        if(txtCMND.getText().equals("")||txtHoTen.getText().equals("")||txtMSSV.getText().equals("")||txtMaLop.getText().equals("")){
            return false;
        }
        return true;
    }
    private void btnThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSVActionPerformed
      if(kiemTra()==false){
          JOptionPane.showMessageDialog(cbLop,"Nhap day du thongh tin");
          return;
      }
        try{
           DkmhId dkmhId=new DkmhId();
           dkmhId.setMaSv(txtMSSV.getText());
           dkmhId.setMaLop(cbLop.getSelectedItem().toString());
           dkmhId.setMaMon(cbDSMH.getSelectedItem().toString());
            Dkmh dkmh=new Dkmh();
            dkmh.setId(dkmhId);
            dkmh.setHoTen(txtHoTen.getText());
            
            dkmh.setStt(tbMonHoc.getRowCount());
            if(rdNam.isSelected()){
                dkmh.setGioiTinh("Nam");
            }else{
                dkmh.setGioiTinh("Nư");
            }

            dkmh.setCmnd(Integer.parseInt(txtCMND.getText()));
            dKMHDAO.add(dkmh);
            JOptionPane.showMessageDialog(cbLop,"Them Thanh cong");
            }catch( Exception e){
                JOptionPane.showMessageDialog(cbLop,"Them That bai");
            }
    }//GEN-LAST:event_btnThemSVActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtHoTen.setText("");
        txtCMND.setText("");
        txtMSSV.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyMH;
    private javax.swing.JButton btnThemSV;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbDSMH;
    private javax.swing.JComboBox cbLop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbMonHoc;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtMaLop;
    // End of variables declaration//GEN-END:variables
}
