/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan_hibernate_qlsv;
import DAO.*;
import entities.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class QLPhucKhao extends javax.swing.JPanel {

    /**
     * Creates new form QLPhucKhao
     */
    String maLop;
    String maMon;
    String maSV;
    QLPhucKhaoDAO qlpkdao=new QLPhucKhaoDAO();
    BangDiemDAO bdDAO=new BangDiemDAO();
    public QLPhucKhao() {
        initComponents();
        load();
    }
    public  void load(){
        loadData();
    }
     private void loadData()
    {
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("STT");
        dtm.addColumn("MSSV");
        dtm.addColumn("Ma Lop");
        dtm.addColumn("Họ Tên");
        dtm.addColumn("Ma Mon");
        dtm.addColumn("GK");
        dtm.addColumn("CK");
        dtm.addColumn("DK");
        dtm.addColumn("Tong ĐIểm");
        dtm.addColumn("Điểm MM");
         dtm.addColumn("Lý Do");
        dtm.addColumn("Tình Trang");
        for(entities.Svphuckhao sv: this.qlpkdao.load_danhSach())
        {
            dtm.addRow(new Object[]{sv.getStt(),sv.getId().getMaSv(),sv.getId().getMaLop(),sv.getHoTen(),sv.getId().getMaMon(),sv.getGiuaKy(),
            sv.getCuoiKy(),sv.getDiemKhac(),sv.getTongDiem(),sv.getDiemMm(),sv.getLyDo(),sv.getTinhTrang()});
            
        }
        this.tbQLPK.setModel(dtm);
        this.tbQLPK.repaint();
        this.tbQLPK.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQLPK = new javax.swing.JTable();
        lbTD = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtGK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDK = new javax.swing.JTextField();
        txtTD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rdOK = new javax.swing.JRadioButton();
        rdNon = new javax.swing.JRadioButton();
        lbMaSV = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbMaLop = new javax.swing.JLabel();
        lbMaMon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Danh Sách Phúc Khảo Sinh Viên Gởi");

        tbQLPK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbQLPK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQLPKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbQLPK);

        lbTD.setBackground(new java.awt.Color(255, 153, 102));
        lbTD.setToolTipText("Cập Nhập Phúc Khảo");

        jLabel2.setText("Giữa Kỳ");

        txtGK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGKKeyReleased(evt);
            }
        });

        jLabel3.setText("Cuối Kỳ");

        txtCK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCKKeyReleased(evt);
            }
        });

        jLabel4.setText("Điểm Khác");

        jLabel5.setText("Tổng Điểm");

        txtDK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDKKeyReleased(evt);
            }
        });

        txtTD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTDKeyReleased(evt);
            }
        });

        jLabel6.setText("Trạng Thái");

        jButton1.setText("Cập Nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");

        buttonGroup1.add(rdOK);
        rdOK.setText("Đã Cập Nhập");

        buttonGroup1.add(rdNon);
        rdNon.setText("Không Cập Nhập");

        lbMaSV.setText("maSV");

        lbHoTen.setText("Ho ten");

        lbMaLop.setText("jLabel8");

        lbMaMon.setText("jLabel8");

        javax.swing.GroupLayout lbTDLayout = new javax.swing.GroupLayout(lbTD);
        lbTD.setLayout(lbTDLayout);
        lbTDLayout.setHorizontalGroup(
            lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbTDLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaLop)
                    .addComponent(lbMaMon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbTDLayout.createSequentialGroup()
                        .addComponent(lbMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbTDLayout.createSequentialGroup()
                        .addComponent(lbHoTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(36, 36, 36)
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(56, 56, 56)
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbTDLayout.createSequentialGroup()
                        .addComponent(txtDK, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6))
                    .addComponent(txtTD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbTDLayout.createSequentialGroup()
                        .addComponent(rdNon)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lbTDLayout.createSequentialGroup()
                        .addComponent(rdOK)
                        .addGap(113, 113, 113)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        lbTDLayout.setVerticalGroup(
            lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbTDLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(rdOK)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(lbMaSV)
                    .addComponent(lbMaLop))
                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbTDLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbTDLayout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbTDLayout.createSequentialGroup()
                                        .addComponent(rdNon)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbTDLayout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(lbTDLayout.createSequentialGroup()
                                .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(lbTDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(lbTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHoTen)
                            .addComponent(lbMaMon))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel7.setText("Cập Nhập SV: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lbTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbQLPKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQLPKMouseClicked
//        String gk=tbQLPK.getValueAt(tbQLPK.getSelectedRow(),5).toString();
//        float ck=Float.parseFloat(tbQLPK.getValueAt(tbQLPK.getSelectedRow(),6).toString());
//        float dk=Float.parseFloat(tbQLPK.getValueAt(tbQLPK.getSelectedRow(),7).toString());
//        float tong=Float.parseFloat(tbQLPK.getValueAt(tbQLPK.getSelectedRow(),8).toString());
        String hoTen=tbQLPK.getValueAt(tbQLPK.getSelectedRow(),3).toString();
        maLop=tbQLPK.getValueAt(tbQLPK.getSelectedRow(),2).toString();
        maMon=tbQLPK.getValueAt(tbQLPK.getSelectedRow(),4).toString();
        maSV=tbQLPK.getValueAt(tbQLPK.getSelectedRow(),1).toString();
//        txtGK.setText(gk);
//        txtCK.setText(String.valueOf(ck));
//        txtDK.setText(String.valueOf(dk));
//        txtTD.setText(String.valueOf(tong));
        lbMaSV.setText(maSV);
        lbHoTen.setText(hoTen);
        lbMaLop.setText(maLop);
        lbMaMon.setText(maMon);
    }//GEN-LAST:event_tbQLPKMouseClicked
    public void lamTrang(){
        txtCK.setText("");
        txtDK.setText("");
        txtGK.setText("");
        txtTD.setText("");
    }
    public  boolean kiemTra(){
        if(txtCK.getText().equals("")||txtDK.getText().equals("")||txtGK.getText().equals("")){
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(rdOK.isSelected()==false&&rdNon.isSelected()==false){
                 JOptionPane.showMessageDialog(this,"Chon Cap Nhap Tinh Trang");
                 return;
            }
        if(rdOK.isSelected()==true){
            try {
                SvphuckhaoId svphuckhaoId=new SvphuckhaoId(maSV, maLop, maMon);
                Svphuckhao svphuckhao =qlpkdao.load(svphuckhaoId);

//                svphuckhao.setGiuaKy(txtGK.getText());
//                svphuckhao.setCuoiKy(Float.parseFloat(txtCK.getText()));
//                svphuckhao.setDiemKhac(Float.parseFloat(txtDK.getText()));
//                svphuckhao.setTongDiem(Float.parseFloat(txtTD.getText()));

                
                    svphuckhao.setTinhTrang("Da Cap Nhap");
                
                qlpkdao.update(svphuckhao);
                if(kiemTra()){
                // cap nhap lai bang diem
                    BangdiemId bangdiemId=new BangdiemId(maLop, maMon, maSV);
                    Bangdiem bd=bdDAO.load(bangdiemId);
                    bd.setGk(Float.parseFloat(txtGK.getText()));
                    bd.setCk(Float.parseFloat(txtCK.getText()));
                    bd.setKhac(Float.parseFloat(txtDK.getText()));
                    bd.setTongDiem(Float.parseFloat(txtTD.getText()));
                    bdDAO.update(bd);
                    JOptionPane.showMessageDialog(this,"Cap Nhap Thanh Cong");
                    load();
                }else{
                    JOptionPane.showMessageDialog(this,"Nhap cac cot diem");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Cap Nhap That Bại");
            }
            lamTrang();
        }
        if(rdNon.isSelected()==true){
            try {
                SvphuckhaoId svphuckhaoId=new SvphuckhaoId(maSV, maLop, maMon);
                Svphuckhao svphuckhao =qlpkdao.load(svphuckhaoId);
                
//                svphuckhao.setGiuaKy(txtGK.getText());
//                svphuckhao.setCuoiKy(Float.parseFloat(txtCK.getText()));
//                svphuckhao.setDiemKhac(Float.parseFloat(txtDK.getText()));
//                svphuckhao.setTongDiem(Float.parseFloat(txtTD.getText()));

//                if(rdOK.isSelected()){
//                    svphuckhao.setTinhTrang("Da Cap Nhap");
//                }else{
                    svphuckhao.setTinhTrang("Khong Cap Nhap");
//                }
                qlpkdao.update(svphuckhao);

                // cap nhap lai bang diem
//                BangdiemId bangdiemId=new BangdiemId(maLop, maMon, maSV);
//                Bangdiem bd=bdDAO.load(bangdiemId);
//                bd.setGk(Float.parseFloat(txtGK.getText()));
//                bd.setCk(Float.parseFloat(txtCK.getText()));
//                bd.setKhac(Float.parseFloat(txtDK.getText()));
//                bd.setTongDiem(Float.parseFloat(txtTD.getText()));
//                bdDAO.update(bd);
//                JOptionPane.showMessageDialog(this,"Cap Nhap Thanh Cong");
                load();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Cap Nhap That Bại");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void tinhTong(){
        float td=0;
            String  gk=txtGK.getText();
            float kq1=Float.parseFloat(gk);
            float kq2=Float.parseFloat( txtCK.getText());
            float kq3=Float.parseFloat( txtDK.getText());
         td=(kq1+kq2+kq3)/3;
         td=Math.round(td);
         txtTD.setText(String.valueOf(td));
    }
    private void txtGKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGKKeyReleased
        tinhTong();
    }//GEN-LAST:event_txtGKKeyReleased

    private void txtCKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCKKeyReleased
        tinhTong();
    }//GEN-LAST:event_txtCKKeyReleased

    private void txtDKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDKKeyReleased
        tinhTong();
    }//GEN-LAST:event_txtDKKeyReleased

    private void txtTDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTDKeyReleased
        tinhTong();
    }//GEN-LAST:event_txtTDKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMaLop;
    private javax.swing.JLabel lbMaMon;
    private javax.swing.JLabel lbMaSV;
    private javax.swing.JPanel lbTD;
    private javax.swing.JRadioButton rdNon;
    private javax.swing.JRadioButton rdOK;
    private javax.swing.JTable tbQLPK;
    private javax.swing.JTextField txtCK;
    private javax.swing.JTextField txtDK;
    private javax.swing.JTextField txtGK;
    private javax.swing.JTextField txtTD;
    // End of variables declaration//GEN-END:variables
}
