package doan_hibernate_qlsv;

import DAO.TKBDAO;
import entities.*;
import DAO.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class TaoPhucKhaoWindow extends javax.swing.JPanel {

    /**
     * Creates new form TaoPhucKhaoWindow
     */
    TKBDAO tkbDAO=new TKBDAO();
    PhucKhaoDAO pkDAO=new PhucKhaoDAO();
    public TaoPhucKhaoWindow() {
        initComponents();
        load();
    }
    public void load(){
        LoadData();
    }
     private void LoadData()
    {
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("STT");
        dtm.addColumn("Ma Lop");
        dtm.addColumn("Ma Mon");
        dtm.addColumn("Ten Mh");
        dtm.addColumn("Ngày Bắt Đầu");
        dtm.addColumn("Ngày Kết Thúc");
       
        for(entities.Phuckhao pk: this.pkDAO.load_danhSach())
        {
            dtm.addRow(new Object[]{pk.getStt(),pk.getId().getMaLop(),pk.getId().getMaMon(),pk.getTenMh(),pk.getNgayBatDau(),pk.getNgayHetHan()});
            
        }
        this.tbDSPH.setModel(dtm);
        this.tbDSPH.repaint();
        this.tbDSPH.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateBatDau = new com.toedter.calendar.JDateChooser();
        dateHetHan = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSPH = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tạo Phúc Khảo Môn Hoc ");
        add(jLabel1);
        jLabel1.setBounds(354, 25, 450, 29);

        jLabel2.setText("Ngày Bắt Đầu ");
        add(jLabel2);
        jLabel2.setBounds(12, 119, 81, 16);

        jLabel3.setText("Ngày Hết Hạn");
        add(jLabel3);
        jLabel3.setBounds(12, 182, 77, 16);
        add(dateBatDau);
        dateBatDau.setBounds(126, 113, 137, 22);
        add(dateHetHan);
        dateHetHan.setBounds(126, 176, 137, 22);

        jButton1.setText("Tạo Danh Sách Phúc Khảo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(51, 253, 202, 36);

        tbDSPH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDSPH);

        add(jScrollPane1);
        jScrollPane1.setBounds(306, 113, 853, 357);

        jLabel4.setText("Danh Sách Sinh Viên Phúc Khảo");
        add(jLabel4);
        jLabel4.setBounds(467, 72, 280, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date dt=new Date();
        for(Monhoc mh : tkbDAO.load_danhSach())
        {
            try{
                Phuckhao pk=new Phuckhao();
                PhuckhaoId phuckhaoId=new PhuckhaoId();
                phuckhaoId.setMaLop(mh.getId().getMaLop());
                phuckhaoId.setMaMon(mh.getId().getMaMon());
                pk.setStt(mh.getStt());
                pk.setId(phuckhaoId);
                pk.setTenMh(mh.getTenMh());
                pk.setNgayBatDau(dateBatDau.getDate());
                pk.setNgayHetHan(dateHetHan.getDate());
                pkDAO.add(pk);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Loi tao phuc khao");
                return;
            }
            
        }
        JOptionPane.showMessageDialog(this,"Tao phuc khao thanh cong");
        try {
            LoadData();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateBatDau;
    private com.toedter.calendar.JDateChooser dateHetHan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDSPH;
    // End of variables declaration//GEN-END:variables
}
