package entities;
// Generated Aug 20, 2019 9:52:04 PM by Hibernate Tools 4.3.1



/**
 * Dkmh generated by hbm2java
 */
public class Dkmh  implements java.io.Serializable {


     private DkmhId id;
     private int stt;
     private String hoTen;
     private String gioiTinh;
     private int cmnd;

    public Dkmh() {
    }

    public Dkmh(DkmhId id, int stt, String hoTen, String gioiTinh, int cmnd) {
       this.id = id;
       this.stt = stt;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
    }
   
    public DkmhId getId() {
        return this.id;
    }
    
    public void setId(DkmhId id) {
        this.id = id;
    }
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public int getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(int cmnd) {
        this.cmnd = cmnd;
    }




}


