package entities;
// Generated Aug 23, 2019 10:11:20 PM by Hibernate Tools 4.3.1



/**
 * Lophoc generated by hbm2java
 */
public class Lophoc  implements java.io.Serializable {


     private String maLop;
     private int stt;

    public Lophoc() {
    }

    public Lophoc(int stt) {
       this.stt = stt;
    }
   
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }




}


