package entities;
// Generated Aug 20, 2019 9:52:04 PM by Hibernate Tools 4.3.1



/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private MonhocId id;
     private int stt;
     private String tenMh;
     private String phongHoc;

    public Monhoc() {
    }

    public Monhoc(MonhocId id, int stt, String tenMh, String phongHoc) {
       this.id = id;
       this.stt = stt;
       this.tenMh = tenMh;
       this.phongHoc = phongHoc;
    }
   
    public MonhocId getId() {
        return this.id;
    }
    
    public void setId(MonhocId id) {
        this.id = id;
    }
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }




}


