package entities;
// Generated Aug 21, 2019 6:05:04 PM by Hibernate Tools 4.3.1



/**
 * MonhocId generated by hbm2java
 */
public class MonhocId  implements java.io.Serializable {


     private String maMon;
     private String maLop;

    public MonhocId() {
    }

    public MonhocId(String maMon, String maLop) {
       this.maMon = maMon;
       this.maLop = maLop;
    }
   
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MonhocId) ) return false;
		 MonhocId castOther = ( MonhocId ) other; 
         
		 return ( (this.getMaMon()==castOther.getMaMon()) || ( this.getMaMon()!=null && castOther.getMaMon()!=null && this.getMaMon().equals(castOther.getMaMon()) ) )
 && ( (this.getMaLop()==castOther.getMaLop()) || ( this.getMaLop()!=null && castOther.getMaLop()!=null && this.getMaLop().equals(castOther.getMaLop()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaMon() == null ? 0 : this.getMaMon().hashCode() );
         result = 37 * result + ( getMaLop() == null ? 0 : this.getMaLop().hashCode() );
         return result;
   }   


}


