package entities;
// Generated Aug 20, 2019 9:52:04 PM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private String maSv;
     private int stt;
     private String hoTen;
     private String gioiTinh;
     private int cmnd;
     private String maLop;

    public Sinhvien() {
    }

    public Sinhvien(String maLop) {
        this.maLop = maLop;
    }
    
    public Sinhvien(String maSv, int stt, String hoTen, String gioiTinh, int cmnd, String maLop) {
       this.maSv = maSv;
       this.stt = stt;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
       this.maLop = maLop;
    }
   
    public String getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(String maSv) {
        this.maSv = maSv;
    }
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public int getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(int cmnd) {
        this.cmnd = cmnd;
    }
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }

    @Override
    public String toString() {
        return maLop;
    }




}


